# product_comments.py

product_comments = {
    "Electronics": [
        "This smartphone has an amazing battery life! I can go a full day with heavy use, and it still has charge left.",
        "The laptop is lightweight and portable, but the fan gets loud when running multiple apps.",
        "The Bluetooth connectivity is seamless. I love how quickly it pairs with my headphones.",
        "I bought this TV for my living room, and the 4K resolution is stunning. Watching movies feels like a theater experience.",
        "The speaker sound quality is decent, but I expected more bass. Works well for casual use.",
        "The camera on this phone is great in daylight but struggles in low light. Still, the features are impressive.",
        "I had some issues with the charging port—it stopped working after a month. Luckily, customer service was helpful.",
        "The tablet is fast and responsive. Great for reading and browsing but not powerful enough for gaming.",
        "I love this smartwatch! It tracks my workouts accurately and syncs well with my phone.",
        "The wireless mouse is very ergonomic, but it disconnects randomly sometimes.",
        "The gaming laptop performs exceptionally well! Smooth graphics and no lag, even with high-performance games.",
        "This power bank is a lifesaver. Charges my phone multiple times and is compact for travel.",
        "The Wi-Fi router has excellent range, but setup was a bit confusing.",
        "I got these noise-canceling headphones, and they are worth every penny! Blocks out all background noise.",
        "This external hard drive is fast and reliable. I use it for backups and have no complaints.",
        "I love my new DSLR camera! The picture quality is outstanding, and it’s easy to use for beginners.",
        "My smart TV integrates well with apps, but sometimes it lags while streaming.",
        "The electric shaver is smooth and doesn’t irritate my skin. Great battery life too.",
        "This smartwatch has great fitness tracking features, but the strap quality could be better.",
        "The drone captures stunning aerial footage! Battery life is short, though.",
        "The wireless keyboard is quiet and comfortable to type on. Works well for long hours.",
        "I upgraded my sound system, and the difference is incredible. Surround sound feels immersive.",
        "The VR headset is next-level! Feels like stepping into another world.",
        "The tablet stand is sturdy and perfect for watching movies or reading hands-free.",
        "The smart doorbell provides clear video and real-time alerts. It enhances security greatly.",
        "I love my new car dashcam! It records crystal-clear footage and provides peace of mind."
    ],
    "Fashion": [
        "I bought this dress for a wedding, and it fits perfectly! The material is comfortable, and the color is vibrant.",
        "The jacket is stylish and warm, but the zipper feels a little flimsy. Hoping it lasts through the winter.",
        "These sneakers are super comfortable for walking long distances. The design is trendy too!",
        "The fabric of this T-shirt is soft and breathable. Perfect for hot weather.",
        "I ordered jeans, and they fit well but have a weird smell out of the box. Washing helped.",
        "The handbag is beautiful and spacious. The strap could be more durable, though.",
        "This hat goes with everything! It’s lightweight and perfect for sunny days.",
        "The heels are elegant but not comfortable for long wear. They look great but need extra padding inside.",
        "I love this scarf! It’s warm, stylish, and a great addition to my winter wardrobe.",
        "The quality of this suit is top-notch! It looks tailored and is worth the price.",
        "The leather belt is durable and looks great with both casual and formal outfits.",
        "These leggings are very stretchy and comfortable, but they run slightly small.",
        "I bought this watch, and it looks so luxurious! Goes well with every outfit.",
        "The gloves are warm and fit well, but the touchscreen feature doesn’t work as expected.",
        "This hoodie is super cozy and great for chilly evenings. I wear it all the time.",
        "These sunglasses are stylish and protect my eyes from the sun effectively.",
        "I love my new boots! They are stylish and comfortable, perfect for winter.",
        "This jumpsuit is flattering and fits just right! Great for both casual and formal events.",
        "I got these earrings, and they are gorgeous! The quality is way better than expected."
    ],
    "Home & Kitchen": [
        "This blender is powerful and blends smoothies perfectly. Cleaning it is a bit tricky, though.",
        "I love this air fryer! It makes crispy fries with very little oil, and it's easy to use.",
        "The set of non-stick pans works well, but they scratch easily if not handled properly.",
        "This coffee maker is a lifesaver in the mornings! Brews coffee quickly and keeps it hot.",
        "The vacuum cleaner has strong suction power and is perfect for pet owners.",
        "These curtains add a nice touch to my room. They block sunlight completely and look stylish.",
        "This dish rack is sturdy and spacious. A great addition to my kitchen.",
        "I love this scented candle! The fragrance lasts long, and it creates a cozy atmosphere.",
        "The knife set is sharp and well-made. The handles feel comfortable to hold.",
        "This microwave is compact and heats food evenly. I use it daily with no issues.",
        "The electric kettle boils water super fast! Great for tea and coffee lovers.",
        "This baking set is perfect for beginners. Comes with everything I need for cookies and cakes.",
        "I bought this sofa cover, and it transformed my living room! Looks stylish and protects my couch.",
        "This rice cooker makes cooking so much easier! Perfect rice every time."
    ],
    "Beauty & Personal Care": [
        "This face cream keeps my skin hydrated all day. No greasy feeling at all.",
        "The shampoo smells amazing and leaves my hair soft and silky.",
        "I love this perfume! It lasts all day and has a refreshing floral scent.",
        "The foundation blends seamlessly into my skin. Perfect for a natural look.",
        "This body lotion is super moisturizing and great for dry skin.",
        "The beard oil helps soften my beard and gives it a healthy shine.",
        "The facial mask makes my skin glow! I use it weekly for the best results.",
        "I love this lipstick! It stays on for hours without fading or smudging.",
        "The deodorant keeps me fresh all day without irritation.",
        "This sunscreen is lightweight and doesn't leave a white cast on my skin.",
        "I bought this hair straightener, and it works wonders! Heats up fast and smoothens my hair instantly."
    ],
    "Books": [
        "This novel kept me hooked from start to finish! A thrilling storyline with great characters.",
        "The self-help book offers amazing insights on personal growth and productivity.",
        "I bought this cookbook, and the recipes are easy to follow with delicious results.",
        "This history book is well-researched and presents the facts in an engaging way.",
        "I love this poetry collection! Each poem is so beautifully written and emotional.",
        "The sci-fi novel is a masterpiece! The world-building is top-notch.",
        "This business book is a must-read for entrepreneurs. Very insightful and practical.",
        "I got this book for my kids, and they love it! The illustrations are colorful and fun."
    ],
    "Sports": [
        "These running shoes are lightweight and provide excellent support during workouts.",
        "I love this yoga mat! It has great grip and is thick enough to protect my knees.",
        "The gym gloves fit well and provide a strong grip when lifting weights.",
        "This football is high quality and feels durable. Great for practice sessions.",
        "The cycling helmet is sturdy and comfortable. A must-have for long rides.",
        "These dumbbells are perfect for home workouts. Good quality and easy to grip.",
        "The basketball has great bounce and grip. Feels like a professional ball.",
        "I bought this resistance band set, and it helps me stretch and strengthen muscles.",
        "This swim cap keeps my hair dry, and the goggles don’t fog up. Great buy!",
        "The tennis racket is lightweight and helps me improve my game.",
        "I love my new hiking backpack! It’s spacious, comfortable, and perfect for long trips.",
        "This sports watch tracks my workouts and calories burned accurately.",
        "The punching bag is sturdy and helps with endurance training.",
        "This golf club set is beginner-friendly and well-balanced."
    ],
    "Toys": [
        "This puzzle set is great for kids! It keeps them engaged for hours.",
        "I bought this dollhouse, and my daughter absolutely loves it!",
        "The RC car is fast and durable. My son plays with it every day.",
        "These building blocks are high-quality and inspire creativity.",
        "The board game is fun for the whole family! We play it every weekend.",
        "This action figure set is well-made and has great detail.",
        "The stuffed animal is so soft and cuddly! My child won’t sleep without it.",
        "This toy kitchen set is perfect for pretend play. Comes with lots of accessories!",
        "I love this musical toy—it plays different melodies and helps kids learn sounds.",
        "The water gun is powerful and great for summer fun!",
        "This LEGO set was a great gift. My kids had so much fun assembling it.",
        "The coloring book has cute designs, and the crayons are easy for toddlers to use.",
        "This scooter is sturdy and safe for kids. My child loves riding it outside!",
        "The science experiment kit is educational and fun! Perfect for curious kids."
    ]
}
